### ISSUE TITLE
ttblue does not work with TomTom Spark/Runner2 (was: socket connect failed?)

### ISSUE THREAD

**Issue by mplusband** [dlenski/ttblue#4]
I was trying to run ttblue to connect to TomTom Spark running watch. I can hcitool lescan the watch's MAC address but ttblue got stuck at creating L2CAP socket. I checked the connect() function fails thus never get to pairing process. 
How should I fix this?

**Comment by dlenski** [comment]
Hi! First of all, I should mention that, to my knowledge, no one has tried `ttblue` yet with anything other than a Runner or MultiSport. That said, I *assume* the BLE protocol used by the Spark is very similar.

Are you saying that the error comes from [https://github.com/dlenski/ttblue/blob/master/ttblue.c#L97](ttblue.c line 97) specifically?

**Comment by mplusband** [comment]
Yes, the error comes from ttblue.c line 97.

**Comment by dlenski** [comment]
Can you tell me what is the error message from `connect()`? (I just made it print the error string and `errno` in f42b57b03465d4d8efa7b15769d1857fca841be9.)

If the error is simply a timeout: the TomTom devices [don't listen for BLE connections very often](https://github.com/dlenski/ttblue/blob/master/tt_bluetooth.md#mysteries), normally **only for 10 seconds every 10 minutes**, except _right_ after completing an activity or when plugged in. The best way to get the device to "wake up and listen" is to go into the menu and press a button or two.

**Comment by mplusband** [comment]
The error is: Failed to connect L2CAP socket: Transport endpoint is not connected (107).

**Comment by dlenski** [comment]
Does it happen immediately, or after a delay? This error ([ENOTCONN](http://kernelhistory.sourcentral.org/linux-1.3.96/S/285.html#L110)) is the "normal" error when the device is not listening for Bluetooth connections. `ttblue` basically just ignores this error when you run in daemon mode because it knows that the device won't be listening for connections most of the time.

Are you *sure* that the device is listening for connections? Can you connect with the Android or iPhone apps without any additional steps?

**Comment by mplusband** [comment]
It happens after a delay. The watch was listening for Bluetooth connections (can be lescaned) when ttblue is running.  
The watch can be connected to an Android phone. During connection the watch displays a pairing code for the phone to pair. After typing the pairing code on the phone, the connection is complete.

**Comment by dlenski** [comment]
Okay, thanks for filling me in. That sounds just like how it works on the Runner/MultiSport. Since all the prior steps succeed (socket creation, bind, security level setting)... I can only think of one other thing that might be different: public vs. random address.

The Runner/MultiSport uses a random address and you can't connect to its public address.

Could you try changing this to a public address (change `BDADDR_LE_RANDOM` to `BDADDR_LE_PUBLIC`) in line 296: https://github.com/dlenski/ttblue/blob/master/ttblue.c#L296

Would be quite interesting if TomTom had changed this, though I have no idea why they would've done it.

**Comment by mplusband** [comment]
Thanks a lot for the advice. But the watch is taken out of office by one of my colleagues now. I will let you know if it works after changing the address to public tomorrow.

**Comment by dlenski** [comment]
Definitely. Unfortunately, it seems likely that a number of things may have changed in the Spark, and I don't have one.

If you are able to use the [Bluetooth snooping feature of Android 4.4+](https://www.nowsecure.com/blog/2014/02/07/bluetooth-packet-capture-on-android-4-4/), then you can record a complete session of interaction between the "official" Android app and the watch.

(That is how I reverse-engineered the protocol for the Runner/MultiSport.)

**Comment by mplusband** [comment]
Awesome! Will definitely try that.

**Comment by mplusband** [comment]
L2capsocket connection is complete after I change BDADDR_LE_RANDOM to BDADDR_LE_PUBLIC in line 296: https://github.com/dlenski/ttblue/blob/master/ttblue.c#L296.
Thanks again!

**Comment by dlenski** [comment]
Wow! Does it actually work fully? Or does it get hung up later in the authentication process? You can dump all the packets being exchanged with `-D -D`, by the way.

**Comment by mplusband** [comment]
It does hang up in the authentication process due to the unmatched device info. Also the protocol part needs to be changed to fit the Spark protocol to make it fully work. But I have not changed that part yet. Since the socket part is clear, the left work won't be much to do, I guess.

**Comment by dlenski** [comment]
You may want to try the latest version of `ttblue`. I fixed a major bug in 49b17050237bcff6bb519797011c3e2cffdb683b.

Basically, I had errors and missing pieces from the authentication/setup sequence which made it somewhere between unreliable and non-functional… I must've been sleep-deprived when I extracted these from the logs, and somehow it worked with my _own_ TomTom, though no one else's.

**Comment by drkingpo** [comment]
Hi there,

having a Runner2 and running in the same issue.
After change BDADDR_LE_RANDOM to BDADDR_LE_PUBLIC in ttblue.c, the Runner 2 generates paring codes, but ttblue jumped into a Loop with Error "hci_le_con update: Input/Output error" and starting search again and Runner 2 generates again a Pairing code.

Anything else I Need to provide to Support?

**Comment by dlenski** [comment]
@drkingpo, that's an odd place for an error. Hmmm.

What happens if you comment out [`ttblue.c` lines 390-405](https://github.com/dlenski/ttblue/blob/master/ttblue.c#L390-L405)?

Ultimately, the only way to figure out the BT protocol for the Runner2 is to get a log of it communicating with the official TomTom apps. This is easy to do on Android:
* Follow these instructions to enable Bluetooth packet capture: http://www.nowsecure.com/blog/2014/02/07/bluetooth-packet-capture-on-android-4-4/
* Record a complete "conversation" between

**Comment by drkingpo** [comment]
> What happens if you comment out ttblue.c lines 390-405 and recompile? Does it get further in the connection process?

It still make the Runner2 to generate an pairing code but result than in:

> Press Enter to continue: 
> 
> Scanning for TomTom BLE devices...
> Opening L2CAP LE connection on ATT channel:
> 	 src: 7C:7A:91:3B:2B:7A
> 	dest: E4:04:39:53:2C:C6
> Could not read device PPCP (handle 0x000b): Input/output error (5)


I'm not having an Android with 4.4, neither (more important BLTH 4.x), but going to speak to some friends who have...

**Comment by dlenski** [comment]
Cool. I'm fairly certain than *any* device which originally came with Android v4.4 or newer has Bluetooth 4.0.

**Comment by dlenski** [comment]
@drkingpo has given me some Android btsnoop logs for a Runner2. I'll be working on support for it in the [`v2_devices` branch](https://github.com/dlenski/ttblue/tree/v2_devices).

**Comment by dlenski** [comment]
Thanks to a lot of logging and debugging help from @drkingpo, `ttblue` now
works with his Spark/Runner v2 with firmware 1.1.19 … it can download
activities and update the QuickFixGPS over Bluetooth Low Energy.

Currently only the [v2_devices branch](
https://github.com/dlenski/ttblue/commits/v2_devices) supports the Runner
v2, not the master branch.

It would be great to have other users test this support!! I don't have a v2
device myself, so I'm dependent on others to check that I've adapted it
correctly.

@derickrethans, @matthiasdallner @mplusband: if any of you has a BT 4.0
adapter and are willing to try it out, it would be excellent to get your
feedback.

What happens if you comment out ttblue.c lines 390-405 and recompile? Does
it get further in the connection process?

It still make the Runner2 to generate an pairing code but result than in:

Press Enter to continue:

Scanning for TomTom BLE devices...
Opening L2CAP LE connection on ATT channel:
src: 7C:7A:91:3B:2B:7A
dest: E4:04:39:53:2C:C6
Could not read device PPCP (handle 0x000b): Input/output error (5)

I'm not having an Android with 4.4, neither (more important BLTH 4.x), but
going to speak to some friends who have...

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/dlenski/ttblue/issues/4#issuecomment-206802727>

**Comment by wsxarcher** [comment]
Just tried.
It downloads the ttbins but it doesn't remove the activities from the watch (I only ran --get-activities).
When the support will be merged into master?

**Comment by dlenski** [comment]
@wsxarcher, are you sure that you're using the latest build from the `v2_devices` branch? I enabled deletion of the activities in 4bdfc031c2d493b6858d0cb2284a3f766161fa44

**Comment by wsxarcher** [comment]
Yes, I'm sure!

**Comment by dlenski** [comment]
Can you send me a log of the output with the `-D`/`--debug` flag?

**Comment by drkingpo** [comment]
@wsxarcher: just to get sure: Which Model and wich FW you use?

**Comment by wsxarcher** [comment]
Yes, I have the 1.1.19 (Spark Cardio+Music).
I didn't had any problem downloading the activities! But I can still see them on the watch.
But if I try to re-do --get-activities, it doesn't get any activities as expected.

**Comment by dlenski** [comment]
> But *I can still see them on the watch.*
> But if I try to re-do --get-activities, *it doesn't get any activities as expected*.

What do you mean by "I can still see them on the watch"? When you go to the `WATCH STATUS` menu (left button) does it show any storage usage? If not, then the activity field *have* been deleted.

The TomTom devices are different from most Garmin devices: they remember a **summary** of an activity even after deleting the **detailed** activity information (`.ttbin` file). 

This seems to a common source of confusion about the TomTom devices (e.g. https://github.com/ryanbinns/ttwatch/issues/60)

**Comment by wsxarcher** [comment]
Sorry you are right! I can only see the summary.
(In the Spark the WATCH STATUS is in the About menu)

**Comment by dlenski** [comment]
Thanks for the quick response, @wsxarcher.

Now that the v2 devices with 1.1.19 firmware are basically working for at least two of you, I'm going to close this issue now.

If more specific issues with the v2 devices are found, please create new issues.
